#--------aplicacion------------------------------------
#nombre de la aplicacion
spring.application.name=farmacia

#-----------configuracion de la base de datos---------
#crea una base H2 en archivo, los datos se conservan al cerrar la aplicación
spring.datasource.url=jdbc:h2:file:C:/Users/salinas/Desktop/jav/Proyecto/Proyecto_farmacia/data_base/farmacia_bbdd
spring.datasource.driverClassName=org.h2.Driver
#usuario y contraseña por defecto para H2
spring.datasource.username=sa
spring.datasource.password=

#----------configuracion de JPA-----------------------
#configura JPA para mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

#----------configuracion de Hibernate-----------------
#le dice a hibernate, si falta una tabla, creala. si existe, actualizala. no borra datos
spring.jpa.hibernate.ddl-auto=update
#configura el dialecto de hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#------------consola web de H2-----------------------
#activa la consola web
spring.h2.console.enabled=true
#ruta para acceder a la consola web de H2
spring.h2.console.path=/h2-console



